version: '3.9'

services:
  mysql:
    image: image
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend
  api-service-dev:
    container_name: api-container-dev
    image: api-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:2004'
    env_file:
      - .env
    networks:
      - backend

#  api-service-test:
#    container_name: api-container-test
#    image: api-image
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - '8081:2004'
#    env_file:
#      - test.env
#    networks:
#      - backend
#
#  api-service-prod:
#    container_name: api-container-prod
#    image: api-image
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - '8082:2004'
#    env_file:
#      - prod.env
#    networks:
#      - backend

networks:
  backend:
    driver: bridge
volumes:
  mysql-data: