server:
  port: 2004
spring:
  config:
    activate:
      on-profile: dev
openapi:
  service:
    api-docs: api-service
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: 1.0.0
    description: API Description
    server: http://localhost:${server.port}
    serverName: ${API_SERVER_NAME:DUMMY-API-SERVER-NAME}
