server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_sample_code
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  config:
    activate:
      on-profile: prod
jwt:
  expiryHour: 1
  expiryDay: 14
  secretKey: b0238cff00a72de79bebabb5b5d6a777ff4b5f0401e6518ea03d48262f4bd818
  refreshKey: 9106746cb1d349b31174dda29c2729d3448d9b8a57418cc1833c8478f0763980
openapi:
  service:
    api-docs: api-service
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: 1.0.0
    description: API Description
    server: http://localhost:${server.port}
    serverName: ${API_SERVER_NAME:DUMMY-API-SERVER-NAME}