server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_sample_code
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  config:
    activate:
      on-profile: test
openapi:
  service:
    api-docs: api-service
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: 1.0.0
    description: API Description
    server: http://localhost:${server.port}
    serverName: ${API_SERVER_NAME:DUMMY-API-SERVER-NAME}