server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
openapi:
  service:
    api-docs: api-service
    title: API Service - Test
    version: 1.0.0
    description: API Description
    server: http://localhost:${server.port}
    serverName: API Test