server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
openapi:
  service:
    api-docs: api-service
    title: API Service - Dev
    version: 1.0.0
    description: API Description
    server: http://localhost:${server.port}
    serverName: API Dev
